specVersion: 0.2.0
name: parallel-bridge-subql
version: 1.0.0
description: ''
repository: 'https://github.com/parallel-finance/parallel-bridge-subql'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x23f4eef686e7b1909f6444f674848b4c1fc2bb9b207f0628bd402f6993a402a6'
  endpoint: 'wss://regnet-rpc.parallel.fi'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridge
