specVersion: 0.2.0
name: parallel-bridge-subql
version: 1.0.0
description: ''
repository: 'https://github.com/parallel-finance/parallel-bridge-subql'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x1a26eee67d758ca045585dcd3203d23704ce69390305d89714094858d65e8244'
  endpoint: 'wss://regnet-rpc.parallel.fi'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridge
